name: motor_vehicle
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_speed_dial: ^5.1.0
  get: ^4.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  month_picker_dialog: ^2.1.0
  intl: ^0.18.1
  date_picker_plus: ^4.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
