name: motor_vehicle
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_speed_dial: ^5.1.0
  get: ^4.6.1
  url_launcher: ^6.3.1
  shared_preferences: ^2.5.3
  http: ^0.13.5
  image_picker: ^0.8.6
  get_storage: ^2.1.1
  intl: ^0.18.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  month_picker_dialog: ^2.1.0
  intl: ^0.18.1
  date_picker_plus: ^4.2.0
  widget_zoom: ^0.0.4


flutter:
  uses-material-design: true

  assets:
    - assets/images/
